package subliminal.panels;

import java.awt.Color;

public class Config extends javax.swing.JPanel {

    public Config() {
        initComponents();
        addButton.setOpaque(false);
        editButton.setVisible(true);
        lClose.setBackground(new Color(0, 0, 0, 0));
        lMinimize.setBackground(new Color(0, 0, 0, 0));
//        
//        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
//            @Override
//            public void mouseEntered(java.awt.event.MouseEvent evt) {
//                addEditPanelMouseEntered(evt);
//            }
//            @Override
//            public void mouseExited(java.awt.event.MouseEvent evt) {
//                addEditPanelMouseExited(evt);
//            }
//        });
//        
//        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
//            @Override
//            public void mouseEntered(java.awt.event.MouseEvent evt) {
//                addEditPanelMouseEntered(evt);
//            }
//            @Override
//            public void mouseExited(java.awt.event.MouseEvent evt) {
//                addEditPanelMouseExited(evt);
//            }
//        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgLocationButtonGroup = new javax.swing.ButtonGroup();
        categoriesButtonGroup = new javax.swing.ButtonGroup();
        timeSettingsPanel = new javax.swing.JPanel();
        displayEveryLabel = new javax.swing.JLabel();
        displayForLabel = new javax.swing.JLabel();
        displayEveryTextField = new javax.swing.JTextField();
        displayForTextField = new javax.swing.JTextField();
        displayEverySecondsLabel = new javax.swing.JLabel();
        displayForMillisLabel = new javax.swing.JLabel();
        messageLocationPanel = new javax.swing.JPanel();
        randomRadioButton = new javax.swing.JRadioButton();
        centerRadioButton = new javax.swing.JRadioButton();
        bottomRadioButton = new javax.swing.JRadioButton();
        categoriesPanel = new javax.swing.JPanel();
        successCheckBox = new javax.swing.JCheckBox();
        successToggleButton = new javax.swing.JToggleButton();
        wightLossToggleButton = new javax.swing.JToggleButton();
        weightLossCheckBox = new javax.swing.JCheckBox();
        addEditPanel = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        lClose = new javax.swing.JLabel();
        lMinimize = new javax.swing.JLabel();

        setBackground(new java.awt.Color(235, 231, 231));
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        timeSettingsPanel.setBackground(new java.awt.Color(246, 244, 244));
        timeSettingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(110, 110, 110))); // NOI18N

        displayEveryLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayEveryLabel.setForeground(new java.awt.Color(110, 110, 110));
        displayEveryLabel.setText("Display Every");

        displayForLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayForLabel.setForeground(new java.awt.Color(110, 110, 110));
        displayForLabel.setText("Display For");
        displayForLabel.setPreferredSize(new java.awt.Dimension(83, 17));

        displayEveryTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayEveryTextField.setPreferredSize(new java.awt.Dimension(34, 17));

        displayForTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayForTextField.setPreferredSize(new java.awt.Dimension(34, 17));

        displayEverySecondsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayEverySecondsLabel.setForeground(new java.awt.Color(110, 110, 110));
        displayEverySecondsLabel.setText("Seconds");
        displayEverySecondsLabel.setPreferredSize(new java.awt.Dimension(83, 17));

        displayForMillisLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayForMillisLabel.setForeground(new java.awt.Color(110, 110, 110));
        displayForMillisLabel.setText("Milliseconds");

        javax.swing.GroupLayout timeSettingsPanelLayout = new javax.swing.GroupLayout(timeSettingsPanel);
        timeSettingsPanel.setLayout(timeSettingsPanelLayout);
        timeSettingsPanelLayout.setHorizontalGroup(
            timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displayForLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayEveryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timeSettingsPanelLayout.createSequentialGroup()
                        .addComponent(displayForTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(timeSettingsPanelLayout.createSequentialGroup()
                        .addComponent(displayEveryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(displayEverySecondsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(displayForMillisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        timeSettingsPanelLayout.setVerticalGroup(
            timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(timeSettingsPanelLayout.createSequentialGroup()
                        .addGroup(timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(displayEveryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                            .addComponent(displayEveryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(displayEverySecondsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayForTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(displayForMillisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(timeSettingsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(displayForLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        messageLocationPanel.setBackground(new java.awt.Color(246, 244, 244));
        messageLocationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message Location", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(110, 110, 110))); // NOI18N

        randomRadioButton.setBackground(new java.awt.Color(246, 244, 244));
        msgLocationButtonGroup.add(randomRadioButton);
        randomRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        randomRadioButton.setText("Display Randomly On Screen");

        centerRadioButton.setBackground(new java.awt.Color(246, 244, 244));
        msgLocationButtonGroup.add(centerRadioButton);
        centerRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        centerRadioButton.setText("Display Center Of Screen");

        bottomRadioButton.setBackground(new java.awt.Color(246, 244, 244));
        msgLocationButtonGroup.add(bottomRadioButton);
        bottomRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bottomRadioButton.setText("Display Bottom Right Of Screen");

        javax.swing.GroupLayout messageLocationPanelLayout = new javax.swing.GroupLayout(messageLocationPanel);
        messageLocationPanel.setLayout(messageLocationPanelLayout);
        messageLocationPanelLayout.setHorizontalGroup(
            messageLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messageLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(randomRadioButton)
                    .addComponent(centerRadioButton)
                    .addComponent(bottomRadioButton))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        messageLocationPanelLayout.setVerticalGroup(
            messageLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageLocationPanelLayout.createSequentialGroup()
                .addComponent(randomRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(centerRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bottomRadioButton))
        );

        categoriesPanel.setBackground(new java.awt.Color(246, 244, 244));
        categoriesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Categories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(110, 110, 110))); // NOI18N
        categoriesPanel.setAutoscrolls(true);

        successCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        categoriesButtonGroup.add(successToggleButton);
        successToggleButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        successToggleButton.setText("Success");
        successToggleButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        categoriesButtonGroup.add(wightLossToggleButton);
        wightLossToggleButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wightLossToggleButton.setText("Weight Loss");
        wightLossToggleButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        weightLossCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        addEditPanel.setBackground(new java.awt.Color(246, 244, 244));
        addEditPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addEditPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addEditPanelMouseExited(evt);
            }
        });

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico_edit.png"))); // NOI18N

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-ico.gif"))); // NOI18N

        javax.swing.GroupLayout addEditPanelLayout = new javax.swing.GroupLayout(addEditPanel);
        addEditPanel.setLayout(addEditPanelLayout);
        addEditPanelLayout.setHorizontalGroup(
            addEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEditPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        addEditPanelLayout.setVerticalGroup(
            addEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editButton)
            .addComponent(addButton)
        );

        javax.swing.GroupLayout categoriesPanelLayout = new javax.swing.GroupLayout(categoriesPanel);
        categoriesPanel.setLayout(categoriesPanelLayout);
        categoriesPanelLayout.setHorizontalGroup(
            categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightLossCheckBox)
                    .addComponent(successCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(categoriesPanelLayout.createSequentialGroup()
                        .addComponent(wightLossToggleButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoriesPanelLayout.createSequentialGroup()
                        .addComponent(successToggleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        categoriesPanelLayout.setVerticalGroup(
            categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriesPanelLayout.createSequentialGroup()
                .addGroup(categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(successCheckBox)
                    .addComponent(successToggleButton)
                    .addComponent(addEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightLossCheckBox)
                    .addComponent(wightLossToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159))
        );

        lClose.setText("X");
        lClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lClose.setName(""); // NOI18N
        lClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCloseMouseClicked(evt);
            }
        });

        lMinimize.setText("-");
        lMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(categoriesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(messageLocationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timeSettingsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(376, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lClose)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lClose)
                    .addComponent(lMinimize))
                .addGap(18, 18, 18)
                .addComponent(timeSettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(messageLocationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoriesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addEditPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEditPanelMouseEntered
        addButton.setVisible(true);
        editButton.setVisible(true);
    }//GEN-LAST:event_addEditPanelMouseEntered

    private void addEditPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEditPanelMouseExited
        addButton.setVisible(false);
        editButton.setVisible(false);
    }//GEN-LAST:event_addEditPanelMouseExited

    private void lCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lCloseMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addEditPanel;
    private javax.swing.JRadioButton bottomRadioButton;
    private javax.swing.ButtonGroup categoriesButtonGroup;
    private javax.swing.JPanel categoriesPanel;
    private javax.swing.JRadioButton centerRadioButton;
    private javax.swing.JLabel displayEveryLabel;
    private javax.swing.JLabel displayEverySecondsLabel;
    private javax.swing.JTextField displayEveryTextField;
    private javax.swing.JLabel displayForLabel;
    private javax.swing.JLabel displayForMillisLabel;
    private javax.swing.JTextField displayForTextField;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel lClose;
    private javax.swing.JLabel lMinimize;
    private javax.swing.JPanel messageLocationPanel;
    private javax.swing.ButtonGroup msgLocationButtonGroup;
    private javax.swing.JRadioButton randomRadioButton;
    private javax.swing.JCheckBox successCheckBox;
    private javax.swing.JToggleButton successToggleButton;
    private javax.swing.JPanel timeSettingsPanel;
    private javax.swing.JCheckBox weightLossCheckBox;
    private javax.swing.JToggleButton wightLossToggleButton;
    // End of variables declaration//GEN-END:variables
}
