package MindCastr.panels;

import MindCastr.components.TransparentLabel;
import MindCastr.dropdown.colorchooser.DropDownColorChooser;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import javax.swing.*;

public class Config extends javax.swing.JPanel {

    String[] envfonts;
    
    public Config() {
        GraphicsEnvironment gEnv = GraphicsEnvironment.getLocalGraphicsEnvironment();
        envfonts = gEnv.getAvailableFontFamilyNames();
        
        initComponents();
        addButton.setOpaque(false);
        editButton.setVisible(true);
        lClose.setBackground(new Color(0, 0, 0, 0));
        lMinimize.setBackground(new Color(0, 0, 0, 0));
        
        updateFontDisplayLabelFont();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgLocationButtonGroup = new javax.swing.ButtonGroup();
        categoriesButtonGroup = new javax.swing.ButtonGroup();
        messageOrderButtonGroup = new javax.swing.ButtonGroup();
        timeSettingsPanel = new javax.swing.JPanel();
        displayEveryLabel = new javax.swing.JLabel();
        displayForLabel = new javax.swing.JLabel();
        displayEveryTextField = new javax.swing.JTextField();
        displayForTextField = new javax.swing.JTextField();
        displayEverySecondsLabel = new javax.swing.JLabel();
        displayForMillisLabel = new javax.swing.JLabel();
        messageLocationPanel = new javax.swing.JPanel();
        randomRadioButton = new javax.swing.JRadioButton();
        centerRadioButton = new javax.swing.JRadioButton();
        bottomRadioButton = new javax.swing.JRadioButton();
        categoriesPanel = new javax.swing.JPanel();
        successCheckBox = new javax.swing.JCheckBox();
        successToggleButton = new javax.swing.JToggleButton();
        wightLossToggleButton = new javax.swing.JToggleButton();
        weightLossCheckBox = new javax.swing.JCheckBox();
        addEditPanel = new javax.swing.JPanel();
        editButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        lClose = new javax.swing.JLabel();
        lMinimize = new javax.swing.JLabel();
        fontPanel = new javax.swing.JPanel();
        fontComboBox = new javax.swing.JComboBox(envfonts);
        fontSizeComboBox = new javax.swing.JComboBox();
        fontDisplayLabel = new TransparentLabel(.99f);
        colorChooserPanel = new DropDownColorChooser(fontDisplayLabel);
        transparencySlider = new javax.swing.JSlider();
        messageOrderPanel = new javax.swing.JPanel();
        orderedCheckBox = new javax.swing.JCheckBox();
        randomCheckBox = new javax.swing.JCheckBox();
        defaultsButton = new javax.swing.JButton();
        doneButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        timeSettingsPanel.setBackground(new java.awt.Color(246, 244, 244));
        timeSettingsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Time Settings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(110, 110, 110))); // NOI18N

        displayEveryLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayEveryLabel.setForeground(new java.awt.Color(110, 110, 110));
        displayEveryLabel.setText("Display Ever");

        displayForLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayForLabel.setForeground(new java.awt.Color(110, 110, 110));
        displayForLabel.setText("Display For");
        displayForLabel.setPreferredSize(new java.awt.Dimension(83, 17));

        displayEveryTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayEveryTextField.setPreferredSize(new java.awt.Dimension(34, 17));

        displayForTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayForTextField.setPreferredSize(new java.awt.Dimension(34, 17));

        displayEverySecondsLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayEverySecondsLabel.setForeground(new java.awt.Color(110, 110, 110));
        displayEverySecondsLabel.setText("Seconds");
        displayEverySecondsLabel.setPreferredSize(new java.awt.Dimension(83, 17));

        displayForMillisLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayForMillisLabel.setForeground(new java.awt.Color(110, 110, 110));
        displayForMillisLabel.setText("Milliseconds");

        javax.swing.GroupLayout timeSettingsPanelLayout = new javax.swing.GroupLayout(timeSettingsPanel);
        timeSettingsPanel.setLayout(timeSettingsPanelLayout);
        timeSettingsPanelLayout.setHorizontalGroup(
            timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displayForLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayEveryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timeSettingsPanelLayout.createSequentialGroup()
                        .addComponent(displayForTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(timeSettingsPanelLayout.createSequentialGroup()
                        .addComponent(displayEveryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(displayEverySecondsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(displayForMillisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        timeSettingsPanelLayout.setVerticalGroup(
            timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timeSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displayEveryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(displayEveryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayEverySecondsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(timeSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(displayForTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(displayForMillisLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(displayForLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        messageLocationPanel.setBackground(new java.awt.Color(246, 244, 244));
        messageLocationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message Location", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(110, 110, 110))); // NOI18N

        randomRadioButton.setBackground(new java.awt.Color(246, 244, 244));
        msgLocationButtonGroup.add(randomRadioButton);
        randomRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        randomRadioButton.setText("Display Randomly On Screen");

        centerRadioButton.setBackground(new java.awt.Color(246, 244, 244));
        msgLocationButtonGroup.add(centerRadioButton);
        centerRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        centerRadioButton.setText("Display Center Of Screen");

        bottomRadioButton.setBackground(new java.awt.Color(246, 244, 244));
        msgLocationButtonGroup.add(bottomRadioButton);
        bottomRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bottomRadioButton.setText("Display Bottom Right Of Screen");

        javax.swing.GroupLayout messageLocationPanelLayout = new javax.swing.GroupLayout(messageLocationPanel);
        messageLocationPanel.setLayout(messageLocationPanelLayout);
        messageLocationPanelLayout.setHorizontalGroup(
            messageLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageLocationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messageLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(randomRadioButton)
                    .addComponent(centerRadioButton)
                    .addComponent(bottomRadioButton))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        messageLocationPanelLayout.setVerticalGroup(
            messageLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageLocationPanelLayout.createSequentialGroup()
                .addComponent(randomRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(centerRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bottomRadioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        categoriesPanel.setBackground(new java.awt.Color(246, 244, 244));
        categoriesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Categories", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(110, 110, 110))); // NOI18N
        categoriesPanel.setAutoscrolls(true);

        successCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        categoriesButtonGroup.add(successToggleButton);
        successToggleButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        successToggleButton.setText("Success");
        successToggleButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        categoriesButtonGroup.add(wightLossToggleButton);
        wightLossToggleButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wightLossToggleButton.setText("Weight Loss");
        wightLossToggleButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        weightLossCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        addEditPanel.setBackground(new java.awt.Color(246, 244, 244));
        addEditPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addEditPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addEditPanelMouseExited(evt);
            }
        });

        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ico_edit.png"))); // NOI18N

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add-ico.gif"))); // NOI18N

        javax.swing.GroupLayout addEditPanelLayout = new javax.swing.GroupLayout(addEditPanel);
        addEditPanel.setLayout(addEditPanelLayout);
        addEditPanelLayout.setHorizontalGroup(
            addEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEditPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        addEditPanelLayout.setVerticalGroup(
            addEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editButton)
            .addComponent(addButton)
        );

        javax.swing.GroupLayout categoriesPanelLayout = new javax.swing.GroupLayout(categoriesPanel);
        categoriesPanel.setLayout(categoriesPanelLayout);
        categoriesPanelLayout.setHorizontalGroup(
            categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightLossCheckBox)
                    .addComponent(successCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(categoriesPanelLayout.createSequentialGroup()
                        .addComponent(wightLossToggleButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, categoriesPanelLayout.createSequentialGroup()
                        .addComponent(successToggleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        categoriesPanelLayout.setVerticalGroup(
            categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoriesPanelLayout.createSequentialGroup()
                .addGroup(categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(successCheckBox)
                    .addComponent(successToggleButton)
                    .addComponent(addEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(categoriesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightLossCheckBox)
                    .addComponent(wightLossToggleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(159, 159, 159))
        );

        lClose.setText("X");
        lClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lClose.setName(""); // NOI18N
        lClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lCloseMouseClicked(evt);
            }
        });

        lMinimize.setText("_");
        lMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        fontPanel.setBackground(new java.awt.Color(246, 244, 244));
        fontPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Font", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(110, 110, 110))); // NOI18N

        fontComboBox.setSelectedIndex(0);
        fontComboBox.setBackground(new java.awt.Color(246, 244, 244));
        fontComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fontComboBox.setForeground(new java.awt.Color(75, 75, 75));
        fontComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontComboBoxActionPerformed(evt);
            }
        });

        fontSizeComboBox.setBackground(new java.awt.Color(246, 244, 244));
        fontSizeComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fontSizeComboBox.setForeground(new java.awt.Color(75, 75, 75));
        fontSizeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "5", "8", "9", "10", "11", "12", "14", "16", "18", "20", "22", "24", "26", "28", "36", "48", "72" }));
        fontSizeComboBox.setSelectedIndex(7);
        fontSizeComboBox.setPreferredSize(new java.awt.Dimension(44, 20));
        fontSizeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontSizeComboBoxActionPerformed(evt);
            }
        });

        fontDisplayLabel.setBackground(new java.awt.Color(246, 244, 244));
        fontDisplayLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fontDisplayLabel.setForeground(new java.awt.Color(110, 110, 110));
        fontDisplayLabel.setText("Font Display");

        colorChooserPanel.setBackground(new java.awt.Color(0, 0, 0));
        colorChooserPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        colorChooserPanel.setForeground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout colorChooserPanelLayout = new javax.swing.GroupLayout(colorChooserPanel);
        colorChooserPanel.setLayout(colorChooserPanelLayout);
        colorChooserPanelLayout.setHorizontalGroup(
            colorChooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
        );
        colorChooserPanelLayout.setVerticalGroup(
            colorChooserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        transparencySlider.setMaximum(99);
        transparencySlider.setPaintTicks(true);
        transparencySlider.setValue(99);
        transparencySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                transparencySliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout fontPanelLayout = new javax.swing.GroupLayout(fontPanel);
        fontPanel.setLayout(fontPanelLayout);
        fontPanelLayout.setHorizontalGroup(
            fontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fontPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fontComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fontSizeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorChooserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(fontDisplayLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transparencySlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fontPanelLayout.setVerticalGroup(
            fontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fontPanelLayout.createSequentialGroup()
                .addGroup(fontPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fontComboBox, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorChooserPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fontSizeComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fontDisplayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transparencySlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        messageOrderPanel.setBackground(new java.awt.Color(246, 244, 244));
        messageOrderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(110, 110, 110))); // NOI18N

        orderedCheckBox.setBackground(new java.awt.Color(246, 244, 244));
        messageOrderButtonGroup.add(orderedCheckBox);
        orderedCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        orderedCheckBox.setForeground(new java.awt.Color(110, 110, 110));
        orderedCheckBox.setSelected(true);
        orderedCheckBox.setText("Ordered");

        randomCheckBox.setBackground(new java.awt.Color(246, 244, 244));
        messageOrderButtonGroup.add(randomCheckBox);
        randomCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        randomCheckBox.setForeground(new java.awt.Color(110, 110, 110));
        randomCheckBox.setText("Random");

        javax.swing.GroupLayout messageOrderPanelLayout = new javax.swing.GroupLayout(messageOrderPanel);
        messageOrderPanel.setLayout(messageOrderPanelLayout);
        messageOrderPanelLayout.setHorizontalGroup(
            messageOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageOrderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(messageOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderedCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(randomCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        messageOrderPanelLayout.setVerticalGroup(
            messageOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(messageOrderPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(orderedCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(randomCheckBox))
        );

        defaultsButton.setLayout(new BorderLayout());
        JLabel label1 = new JLabel("Set To Defaults");
        label1.setFont(new java.awt.Font("Tahoma", 0, 14));
        label1.setForeground(new java.awt.Color(255, 255, 255));
        JLabel label2 = new JLabel("(Recommended)");
        label2.setFont(new java.awt.Font("Tahoma", 0, 9));
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        defaultsButton.add(BorderLayout.NORTH, label1);
        defaultsButton.add(BorderLayout.SOUTH, label2);
        defaultsButton.setBackground(new java.awt.Color(153, 153, 153));
        defaultsButton.setForeground(new java.awt.Color(110, 110, 110));

        doneButton.setBackground(new java.awt.Color(200, 0, 0));
        doneButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        doneButton.setForeground(new java.awt.Color(255, 255, 255));
        doneButton.setText("All Done!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lMinimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lClose)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeSettingsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(messageLocationPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(categoriesPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fontPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(defaultsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(doneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lClose)
                    .addComponent(lMinimize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(doneButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(defaultsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(timeSettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(messageLocationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(categoriesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(fontPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(messageOrderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addEditPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEditPanelMouseEntered
        addButton.setVisible(true);
        editButton.setVisible(true);
    }//GEN-LAST:event_addEditPanelMouseEntered

    private void addEditPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEditPanelMouseExited
        addButton.setVisible(false);
        editButton.setVisible(false);
    }//GEN-LAST:event_addEditPanelMouseExited

    private void lCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lCloseMouseClicked

    private void fontSizeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontSizeComboBoxActionPerformed
        String fontSizeStr = (String)fontSizeComboBox.getSelectedItem();
        float fontSize = Float.parseFloat(fontSizeStr);
        Font newFont = fontDisplayLabel.getFont().deriveFont(fontSize); 
        fontDisplayLabel.setFont(newFont);
    }//GEN-LAST:event_fontSizeComboBoxActionPerformed

    private void transparencySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_transparencySliderStateChanged
        int sliderValue = transparencySlider.getValue();
        float transparencyFactor = sliderValue/100f;
        assert(fontDisplayLabel instanceof TransparentLabel);
        ((TransparentLabel)fontDisplayLabel).changeTransparency(transparencyFactor);
    }//GEN-LAST:event_transparencySliderStateChanged

    private void fontComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontComboBoxActionPerformed
        updateFontDisplayLabelFont();
    }//GEN-LAST:event_fontComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addEditPanel;
    private javax.swing.JRadioButton bottomRadioButton;
    private javax.swing.ButtonGroup categoriesButtonGroup;
    private javax.swing.JPanel categoriesPanel;
    private javax.swing.JRadioButton centerRadioButton;
    private javax.swing.JPanel colorChooserPanel;
    private javax.swing.JButton defaultsButton;
    private javax.swing.JLabel displayEveryLabel;
    private javax.swing.JLabel displayEverySecondsLabel;
    private javax.swing.JTextField displayEveryTextField;
    private javax.swing.JLabel displayForLabel;
    private javax.swing.JLabel displayForMillisLabel;
    private javax.swing.JTextField displayForTextField;
    private javax.swing.JButton doneButton;
    private javax.swing.JButton editButton;
    private javax.swing.JComboBox fontComboBox;
    private javax.swing.JLabel fontDisplayLabel;
    private javax.swing.JPanel fontPanel;
    private javax.swing.JComboBox fontSizeComboBox;
    private javax.swing.JLabel lClose;
    private javax.swing.JLabel lMinimize;
    private javax.swing.JPanel messageLocationPanel;
    private javax.swing.ButtonGroup messageOrderButtonGroup;
    private javax.swing.JPanel messageOrderPanel;
    private javax.swing.ButtonGroup msgLocationButtonGroup;
    private javax.swing.JCheckBox orderedCheckBox;
    private javax.swing.JCheckBox randomCheckBox;
    private javax.swing.JRadioButton randomRadioButton;
    private javax.swing.JCheckBox successCheckBox;
    private javax.swing.JToggleButton successToggleButton;
    private javax.swing.JPanel timeSettingsPanel;
    private javax.swing.JSlider transparencySlider;
    private javax.swing.JCheckBox weightLossCheckBox;
    private javax.swing.JToggleButton wightLossToggleButton;
    // End of variables declaration//GEN-END:variables

    private void updateFontDisplayLabelFont() {
        int selectedIndex = fontComboBox.getSelectedIndex();
        String selectedFontName = envfonts[selectedIndex];
        Font oldFont = fontDisplayLabel.getFont();
        Font newFont = new Font(selectedFontName, oldFont.getStyle(), oldFont.getSize());
        fontDisplayLabel.setFont(newFont);
    }
}
