DEBUG = True
CSRF_ENABLED = True
SECRET_KEY = 'you-will-never-guess'
FILENAME = "mindcastr_settings.json"
UPLOAD_FOLDER = ""
ALLOWED_IMAGE_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])
IMAGE1 = 'ads_1.jpg'
IMAGE2 = 'ads_2.jpg'
ALLOWED_UPDATEFILE_EXTENSIONS = set(['zip'])
UPDATE_FILE1 = 'update_win.zip'
UPDATE_FILE2 = 'update_mac.zip'
